version: "3"                                                              
services:                                                                 
  web:                                                                    
    # replace username/repo:tag with your name and image details          
    image: amitvashist7/myapacheericsson18may21:v2             
    deploy:                                                               
      replicas: 2                                                        
      resources:                                                          
        limits:                                                           
          cpus: "0.1"                                                     
          memory: 50M                                                     
      restart_policy:                                                     
        condition: on-failure                                             
    ports:                                                                
      - "8081:80"                                                           
    networks:                                                             
      - webnet                                                            
networks:                                                                 
  webnet:                     
